language: rust
sudo: false

rust:
  - stable
  - beta

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libbfd-dev
      - libiberty-dev

before_install:
  - export RUST_SRC_PATH=$(scripts/download_rust_source.sh)

before_script:
  - |
    pip install 'travis-cargo<0.2' --user
    export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo test
  - scripts/assert_cargo_lock_unchanged

after_success:
  # - travis-cargo --only stable coveralls --no-sudo --verify
  - git clone https://github.com/SimonKagstrom/kcov
  - |
    export LOCAL="~/.local"
    export PATH=$LOCAL/bin:$PATH
  - |
    mkdir kcov/build
    pushd kcov/build
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL ..
    make
    make install
    popd
  - kcov --verify --no-sudo --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/lib-*
